ALTER SESSION SET CONTAINER = XEPDB1;

CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_TRANS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE GRU.GRU_REJECT_TAB_SEQ START WITH 1 INCREMENT BY 1;