ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE GRU.GRU_VISTA_TAB
(
  ID                 NUMBER(12),
  SYSTEMACCOUNT      VARCHAR2(32 BYTE),
  CURRENCY           VARCHAR2(3 BYTE),
  XALFA             NUMBER(23,3),
  OPERATION          VARCHAR2(3 BYTE),
  TIME_STAMP         DATE                       DEFAULT sysdate,
  POM_ID             NUMBER(12),
  UTERRARIO          NUMBER(18),
  OLDTBAL            NUMBER(23,3),
  NEWTBAL            NUMBER(23,3),
  ADD_INFO           VARCHAR2(100 BYTE),
  FILE_ID            NUMBER(12),
  FOC_STATUS        VARCHAR2(64 BYTE)          DEFAULT 'WAIT',
  FOC_TS            DATE,
  FOC_TYPE          VARCHAR2(10 BYTE)          DEFAULT 'IMMEDIATE'
);