ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS
(
  ID         NUMBER,
  TRANS_ID   NUMBER(18),
  MSG_TYPE   VARCHAR2(64 BYTE),
  DIR        VARCHAR2(16 BYTE),
  MSG        CLOB,
  INS_TS     DATE                               DEFAULT sysdate,
  NODE_ID    VARCHAR2(8 BYTE)
);