ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG
(
  ID               NUMBER(12),
  SYSTEMID         VARCHAR2(255 BYTE),
  EVENT_TYPE       VARCHAR2(255 BYTE),
  ENTITY_TYPE      VARCHAR2(255 BYTE),
  TOPIC_IN         VARCHAR2(255 BYTE),
  STATUS_IN        NUMBER(1),
  TOPIC_OUT        VARCHAR2(255 BYTE),
  STATUS_OUT       NUMBER(1),
  INS_TS           DATE,
  UPD_TS           DATE
);