ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS
(
  ID          NUMBER,
  SYSTEM_ID   VARCHAR2(256 BYTE),
  REQUEST_ID  VARCHAR2(256 BYTE),
  EVENT_TYPE  VARCHAR2(256 BYTE),
  DATA        CLOB,
  STATUS      VARCHAR2(256 BYTE),
  RESP_CODE   VARCHAR2(16 BYTE),
  RESP_DESC   VARCHAR2(256 BYTE),
  INS_TS      DATE                              DEFAULT sysdate,
  UPD_TS      DATE                              DEFAULT sysdate
);