ALTER SESSION SET CONTAINER = XEPDB1;

GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_CONFIG TO GRU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_TRANS TO GRU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS TO GRU;
GRANT SELECT ON ACC_APP_ADAPTER.APP_ADAPTER_TRANS_SEQ TO GRU;
GRANT SELECT ON ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS_SEQ TO GRU;