CREATE SCHEMA IF NOT EXISTS pom;

CREATE SEQUENCE IF NOT EXISTS pom.pom_file_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE;


CREATE SEQUENCE IF NOT EXISTS POM.POM_UNIT_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE;


CREATE SEQUENCE IF NOT EXISTS POM.POM_UNIT_ERROR_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE;


